-- 코드를 작성해주세요
SELECT SUM(FISH_COUNT) AS FISH_COUNT FROM (SELECT COUNT(FISH_NAME) AS FISH_COUNT
FROM FISH_INFO I JOIN FISH_NAME_INFO N WHERE I.FISH_TYPE = N.FISH_TYPE
GROUP BY FISH_NAME
HAVING FISH_NAME IN ('BASS', 'SNAPPER')) F