-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD B JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
WHERE F.BOARD_ID = (SELECT BOARD_ID
                  FROM USED_GOODS_BOARD
                  GROUP BY BOARD_ID
                   ORDER BY VIEWS DESC
                   LIMIT 1)
ORDER BY FILE_ID DESC